"""Update enrollment model relationships

Revision ID: eee59318681e
Revises: 99f4790f2d5d
Create Date: 2025-04-26 21:04:52.392962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee59318681e'
down_revision = '99f4790f2d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('enrollment_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('program_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'program_id')
    )
    # ### end Alembic commands ###
